In [33]:
import pandas as pd
import pandas as np

In [35]:
df = pd.read_csv('dulieuxettuyendaihoc.csv', index_col="STT")
df.head(10)

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,6.6,7.6,5.9,F,NaN,2NT,3.25,3.25,4.50,A1
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,6.6,6.1,4.4,M,NaN,1,6.00,4.00,3.50,C
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,7.9,8.1,4.6,M,NaN,1,5.00,6.75,4.00,C
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,7.1,7.3,7.4,M,NaN,1,4.25,4.25,5.25,D1
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.1,7.5,7.2,M,NaN,2NT,4.25,4.50,5.00,A
6,9.3,7.6,7.9,8.6,7.0,7.3,7.7,7.9,9.6,7.8,...,5.7,8.0,7.8,M,NaN,1,1.50,4.00,6.00,D1
7,2.8,3.9,5.5,6.9,5.0,7.3,4.6,5.2,4.4,6.7,...,6.6,6.0,6.0,F,NaN,2,6.50,6.75,5.25,C
8,8.3,6.0,7.6,5.1,7.5,4.7,5.8,7.2,6.7,6.3,...,7.1,6.8,7.0,F,NaN,2,3.75,4.50,4.25,D1
9,6.5,6.3,7.6,6.0,5.5,7.1,6.3,5.0,7.3,6.8,...,9.1,7.9,6.1,F,NaN,1,3.50,3.50,6.75,D1
10,7.3,5.9,4.7,7.1,6.7,7.9,6.7,7.7,8.0,6.8,...,6.4,6.1,7.8,F,NaN,1,4.00,4.75,5.50,D1

In [36]:
df['DT']. fillna(0,inplace=True)
df.tail(10)

/tmp/ipykernel_627/919757329.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['DT']. fillna(0,inplace=True)

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
STT,,,,,,,,,,,,,,,,,,,,,
91,8.1,7.7,9.1,8.5,6.1,8.6,8.8,7.3,8.8,8.3,...,8.3,8.7,7.8,M,0.0,2,6.25,4.00,6.50,A
92,7.8,6.5,6.7,5.4,6.2,4.8,5.9,4.4,8.9,6.9,...,7.2,7.4,7.0,M,0.0,2NT,4.75,4.75,4.50,A
93,5.0,6.6,6.5,7.2,5.8,6.7,6.4,6.0,6.8,6.1,...,5.9,6.7,5.8,M,0.0,1,3.25,5.25,4.25,A
94,5.2,5.2,6.8,7.9,6.6,8.9,7.6,5.3,6.8,5.8,...,8.7,7.8,5.0,M,0.0,1,3.50,4.25,5.00,A
95,5.8,5.9,7.6,6.1,5.3,8.1,6.1,5.0,6.4,7.2,...,7.3,6.8,5.3,M,0.0,1,4.25,2.50,4.75,A
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,6.3,6.1,6.2,F,0.0,1,5.25,1.50,6.25,C
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,7.9,7.5,4.4,F,0.0,1,5.25,3.75,4.75,C
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,9.6,8.4,5.8,M,0.0,2NT,7.00,8.00,4.00,C
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,6.6,5.2,5.9,M,0.0,1,5.00,3.50,5.50,C
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.6,6.6,5.8,M,0.0,2NT,5.25,2.50,4.25,C

In [39]:
df = pd.read_csv("dulieuxettuyendaihoc.csv", index_col="STT")

print("10 dòng đầu tiên:\n", df.head(10))

10 dòng đầu tiên:
       T1   L1   H1   S1   V1   X1   D1   N1   T2   L2  ...   X6   D6   N6  GT  \
STT                                                    ...
1    7.2  7.3  6.3  7.3  7.0  7.9  7.3  5.5  8.4  8.9  ...  6.6  7.6  5.9   F
2    5.4  3.9  3.9  4.0  5.4  5.4  5.3  2.8  6.3  5.4  ...  6.6  6.1  4.4   M
3    5.6  6.8  7.2  7.5  4.3  7.4  5.8  3.2  5.0  4.9  ...  7.9  8.1  4.6   M
4    6.6  6.4  5.3  6.9  5.4  7.3  6.4  5.8  5.1  6.2  ...  7.1  7.3  7.4   M
5    6.0  5.0  6.0  7.3  6.5  7.7  7.9  6.1  5.4  5.5  ...  6.1  7.5  7.2   M
6    9.3  7.6  7.9  8.6  7.0  7.3  7.7  7.9  9.6  7.8  ...  5.7  8.0  7.8   M
7    2.8  3.9  5.5  6.9  5.0  7.3  4.6  5.2  4.4  6.7  ...  6.6  6.0  6.0   F
8    8.3  6.0  7.6  5.1  7.5  4.7  5.8  7.2  6.7  6.3  ...  7.1  6.8  7.0   F
9    6.5  6.3  7.6  6.0  5.5  7.1  6.3  5.0  7.3  6.8  ...  9.1  7.9  6.1   F
10   7.3  5.9  4.7  7.1  6.7  7.9  6.7  7.7  8.0  6.8  ...  6.4  6.1  7.8   F

     DT   KV   DH1   DH2   DH3  KT
STT
1   NaN  2NT  3.25  3.25  4.50  A1
2   NaN    1  6.00  4.00  3.50   C
3   NaN    1  5.00  6.75  4.00   C
4   NaN    1  4.25  4.25  5.25  D1
5   NaN  2NT  4.25  4.50  5.00   A
6   NaN    1  1.50  4.00  6.00  D1
7   NaN    2  6.50  6.75  5.25   C
8   NaN    2  3.75  4.50  4.25  D1
9   NaN    1  3.50  3.50  6.75  D1
10  NaN    1  4.00  4.75  5.50  D1

[10 rows x 55 columns]

In [42]:
df = pd.read_csv("dulieuxettuyendaihoc.csv", index_col="STT")
print("Số giá trị thiếu của DT:", df["DT"].isnull().sum())
df["DT"] = df["DT"].fillna(0)
print("Sau xử lý:", df["DT"].isnull().sum())

Số giá trị thiếu của DT: 97
Sau xử lý: 0

In [46]:
df["T1"].fillna(df["T1"].mean(), inplace=True)
df

/tmp/ipykernel_627/525574206.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["T1"].fillna(df["T1"].mean(), inplace=True)

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,6.6,7.6,5.9,F,NaN,2NT,3.25,3.25,4.50,A1
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,6.6,6.1,4.4,M,NaN,1,6.00,4.00,3.50,C
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,7.9,8.1,4.6,M,NaN,1,5.00,6.75,4.00,C
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,7.1,7.3,7.4,M,NaN,1,4.25,4.25,5.25,D1
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.1,7.5,7.2,M,NaN,2NT,4.25,4.50,5.00,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,6.3,6.1,6.2,F,NaN,1,5.25,1.50,6.25,C
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,7.9,7.5,4.4,F,NaN,1,5.25,3.75,4.75,C
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,9.6,8.4,5.8,M,NaN,2NT,7.00,8.00,4.00,C
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,6.6,5.2,5.9,M,NaN,1,5.00,3.50,5.50,C
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.6,6.6,5.8,M,NaN,2NT,5.25,2.50,4.25,C

In [48]:
df = df.fillna(df.mean(numeric_only=True))
print(df.isnull().sum())

T1     0
L1     0
H1     0
S1     0
V1     0
X1     0
D1     0
N1     0
T2     0
L2     0
H2     0
S2     0
V2     0
X2     0
D2     0
N2     0
T3     0
L3     0
H3     0
S3     0
V3     0
X3     0
D3     0
N3     0
T4     0
L4     0
H4     0
S4     0
V4     0
X4     0
D4     0
N4     0
T5     0
L5     0
H5     0
S5     0
V5     0
X5     0
D5     0
N5     0
T6     0
L6     0
H6     0
S6     0
V6     0
X6     0
D6     0
N6     0
GT     0
DT     0
KV     0
DH1    0
DH2    0
DH3    0
KT     0
dtype: int64

In [57]:
df["TBM1"] = (df["T1"]*2 + df["L1"] + df["H1"] + df["S1"] + df["V1"]*2 + df["X1"] + df["D1"] + df["N1"]) / 10
df["TBM2"] = (df["T2"]*2 + df["L2"] + df["H2"] + df["S2"] + df["V2"]*2 + df["X2"] + df["D2"] + df["N2"]) / 10
df["TBM3"] = (df["T3"]*2 + df["L3"] + df["H3"] + df["S3"] + df["V3"]*2 + df["X3"] + df["D3"] + df["N3"]) / 10
df[["TBM1", "TBM2", "TBM3"]].head()

     TBM1  TBM2  TBM3
STT
1    7.00  7.54  7.06
2    4.69  5.47  4.70
3    5.77  5.38  4.33
4    6.21  5.20  6.03
5    6.50  6.36  7.01

In [62]:
import numpy as np
def xep_loai(tbm):
    return np.select(
        [
            tbm < 5,
            tbm < 6.5,
            tbm < 8,
            tbm < 9,
            tbm >= 9
        ],
        ["Y", "TB", "K", "G", "XS"],
        default=''
    )

df["XL1"] = xep_loai(df["TBM1"])
df["XL2"] = xep_loai(df["TBM2"])
df["XL3"] = xep_loai(df["TBM3"])
df[["TBM1", "XL1", "TBM2", "XL2", "TBM3", "XL3"]].head()

     TBM1 XL1  TBM2 XL2  TBM3 XL3
STT
1    7.00   K  7.54   K  7.06   K
2    4.69   Y  5.47  TB  4.70   Y
3    5.77  TB  5.38  TB  4.33   Y
4    6.21  TB  5.20  TB  6.03  TB
5    6.50   K  6.36  TB  7.01   K

In [64]:
df["US_TBM1"] = (df["TBM1"] - 0) / (10 - 0) * 4
df["US_TBM2"] = (df["TBM2"] - 0) / (10 - 0) * 4
df["US_TBM3"] = (df["TBM3"] - 0) / (10 - 0) * 4
df[["TBM1", "US_TBM1", "TBM2", "US_TBM2", "TBM3", "US_TBM3"]].head()

     TBM1  US_TBM1  TBM2  US_TBM2  TBM3  US_TBM3
STT
1    7.00    2.800  7.54    3.016  7.06    2.824
2    4.69    1.876  5.47    2.188  4.70    1.880
3    5.77    2.308  5.38    2.152  4.33    1.732
4    6.21    2.484  5.20    2.080  6.03    2.412
5    6.50    2.600  6.36    2.544  7.01    2.804

In [66]:
def tinh_kqxt(row):
    if row["KT"] in ["A", "A1"]:
        diem = (row["DH1"]*2 + row["DH2"] + row["DH3"]) / 4
    elif row["KT"] == "B":
        diem = (row["DH1"] + row["DH2"]*2 + row["DH3"]) / 4
    else:
        diem = (row["DH1"] + row["DH2"] + row["DH3"]) / 3

    return 1 if diem >= 5 else 0

df["KQXT"] = df.apply(tinh_kqxt, axis=1)
df[["KT", "DH1", "DH2", "DH3", "KQXT"]].head(10)

     KT   DH1   DH2   DH3  KQXT
STT
1    A1  3.25  3.25  4.50     0
2     C  6.00  4.00  3.50     0
3     C  5.00  6.75  4.00     1
4    D1  4.25  4.25  5.25     0
5     A  4.25  4.50  5.00     0
6    D1  1.50  4.00  6.00     0
7     C  6.50  6.75  5.25     1
8    D1  3.75  4.50  4.25     0
9    D1  3.50  3.50  6.75     0
10   D1  4.00  4.75  5.50     0